# Generated by Django 4.2 on 2024-09-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=150, verbose_name="Название продукта"),
                ),
                ("model", models.CharField(max_length=150, verbose_name="Модель")),
                (
                    "product_launch_date",
                    models.DateTimeField(verbose_name="Дата выхода на рынок"),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.network",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт розничной сети",
                "verbose_name_plural": "Продукты розничных сетей",
            },
        ),
        migrations.CreateModel(
            name="FactoryProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=150, verbose_name="Название продукта"),
                ),
                ("model", models.CharField(max_length=150, verbose_name="Модель")),
                (
                    "product_launch_date",
                    models.DateTimeField(verbose_name="Дата выхода на рынок"),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.factory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт завода",
                "verbose_name_plural": "Продукты завода",
            },
        ),
        migrations.CreateModel(
            name="BusinessmanProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=150, verbose_name="Название продукта"),
                ),
                ("model", models.CharField(max_length=150, verbose_name="Модель")),
                (
                    "product_launch_date",
                    models.DateTimeField(verbose_name="Дата выхода на рынок"),
                ),
                (
                    "entrepreneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="trading.businessman",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт индивидуального предпринимателя",
                "verbose_name_plural": "Продукты индивидуальных предпринимателей",
            },
        ),
    ]
